# frozen_string_literal: true

# Provides field-level provenance tracking for canonical models.
#
# This concern allows models to track which data source provided each field's value,
# along with the confidence score at the time of the merge. This enables:
# - Transparency about where data originated
# - Conflict resolution based on trust scores
# - Audit trails for data quality
#
# The provenance data is stored in the `field_provenance` JSONB column with the following structure:
# {
#   "field_name": {
#     "source_type": "VRSDataOperatorSource",
#     "source_id": 123,
#     "confidence": 85,
#     "combined_at": "2024-12-24T10:30:00Z"
#   }
# }
#
# @example Usage in a model
#   class Operator < ApplicationRecord
#     include HasFieldProvenance
#   end
#
# @example Getting provenance for a field
#   operator.provenance_for(:name)
#   # => { "source_type" => "VRSDataOperatorSource", "source_id" => 123, "confidence" => 85, ... }
#
# @example Setting provenance for a field
#   operator.set_provenance(:name, source: vrs_record, confidence: 85)
module HasFieldProvenance
  extend ActiveSupport::Concern

  PROVENANCE_KEYS = %w[source_type source_id confidence combined_at].freeze

  # Source type used for auto-generated stub records
  AUTO_GENERATED_SOURCE = 'AutoGenerated'

  # Source type for timezone derived from coordinates via WhereTZ.
  # Data sourced from OpenStreetMap via timezone-boundary-builder project.
  # See: https://github.com/evansiroky/timezone-boundary-builder
  TIMEZONE_BOUNDARY_SOURCE = 'OpenStreetMap/TimezoneBoundaryBuilder'

  included do
    # Ensure the model has the required columns
    # This will raise an error at load time if the migration hasn't been run
    after_initialize :validate_provenance_columns, if: :new_record?

    # Finds records where a specific field has a given source type in its provenance.
    #
    # @param field [Symbol, String] The field name to check
    # @param source_type [String] The source type to match
    # @return [ActiveRecord::Relation]
    #
    # @example Find operators with name from VRS data
    #   Operator.with_field_source(:name, 'VRSDataOperatorSource')
    scope :with_field_source, lambda { |field, source_type|
      where("field_provenance -> ? ->> 'source_type' = ?", field.to_s, source_type)
    }

    # Finds records that were auto-generated and need enrichment from real data sources.
    # These are stub records created when a reference was needed but the canonical
    # record didn't exist.
    #
    # @param field [Symbol, String] The field to check (default: 'name')
    # @return [ActiveRecord::Relation]
    #
    # @example Find all auto-generated manufacturers
    #   Manufacturer.needs_enrichment
    #
    # @example Find manufacturers with auto-generated ICAO codes
    #   Manufacturer.needs_enrichment(:icao_code)
    scope :needs_enrichment, lambda { |field = :name|
      with_field_source(field, AUTO_GENERATED_SOURCE)
    }
  end

  # Returns the provenance hash for a specific field.
  #
  # @param field [Symbol, String] The field name to look up
  # @return [Hash, nil] The provenance data or nil if not tracked
  def provenance_for(field)
    field_provenance[field.to_s]
  end

  # Returns the source class name that provided the value for a field.
  #
  # @param field [Symbol, String] The field name
  # @return [String, nil] The source class name (e.g., "VRSDataOperatorSource")
  def provenance_source_for(field)
    provenance_for(field)&.dig('source_type')
  end

  # Returns the confidence score for a field's value.
  #
  # @param field [Symbol, String] The field name
  # @return [Integer, nil] The confidence score (0-100)
  def provenance_confidence_for(field)
    provenance_for(field)&.dig('confidence')
  end

  # Returns the source record ID that provided the value for a field.
  #
  # @param field [Symbol, String] The field name
  # @return [Integer, nil] The source record ID
  def provenance_source_id_for(field)
    provenance_for(field)&.dig('source_id')
  end

  # Returns when the field was last combined from sources.
  #
  # @param field [Symbol, String] The field name
  # @return [Time, nil] The timestamp of the last combine operation
  def provenance_combined_at_for(field)
    timestamp = provenance_for(field)&.dig('combined_at')
    Time.zone.parse(timestamp) if timestamp
  end

  # Sets the provenance data for a specific field.
  #
  # @param field [Symbol, String] The field name
  # @param source [ApplicationRecord] The source record that provided the value
  # @param confidence [Integer] The trust/confidence score (0-100)
  # @return [Hash] The provenance hash that was set
  def set_provenance(field, source:, confidence:)
    provenance_hash = {
      'source_type' => source.class.name.demodulize,
      'source_id' => source.id,
      'confidence' => confidence,
      'combined_at' => Time.current.iso8601
    }

    # Use a dup to ensure ActiveRecord detects the change
    new_provenance = field_provenance.dup
    new_provenance[field.to_s] = provenance_hash
    self.field_provenance = new_provenance

    provenance_hash
  end

  # Sets provenance for multiple fields at once.
  #
  # @param fields [Array<Symbol, String>] The field names
  # @param source [ApplicationRecord] The source record
  # @param confidence [Integer] The confidence score
  # @return [Hash] The updated field_provenance hash
  def set_provenance_for_fields(fields, source:, confidence:)
    fields.each { |field| set_provenance(field, source: source, confidence: confidence) }
    field_provenance
  end

  # Sets provenance for a field derived from an external source (not a source record).
  # Used for values calculated or looked up from external data (e.g. timezone from coordinates).
  #
  # @param field [Symbol, String] The field name
  # @param source_name [String] The source identifier (e.g. TIMEZONE_BOUNDARY_SOURCE)
  # @param confidence [Integer] The trust/confidence score (0-100)
  # @return [Hash] The provenance hash that was set
  def set_derived_provenance(field, source_name:, confidence:)
    provenance_hash = {
      'source_type' => source_name,
      'source_id' => nil,
      'confidence' => confidence,
      'combined_at' => Time.current.iso8601
    }

    new_provenance = field_provenance.dup
    new_provenance[field.to_s] = provenance_hash
    self.field_provenance = new_provenance

    provenance_hash
  end

  # Clears provenance data for a specific field.
  #
  # @param field [Symbol, String] The field name
  def clear_provenance(field)
    new_provenance = field_provenance.dup
    new_provenance.delete(field.to_s)
    self.field_provenance = new_provenance
  end

  # Returns all fields that have provenance data.
  #
  # @return [Array<String>] List of field names with provenance
  def tracked_fields
    field_provenance.keys
  end

  # Checks if a field has provenance data.
  #
  # @param field [Symbol, String] The field name
  # @return [Boolean]
  def has_provenance?(field)
    field_provenance.key?(field.to_s)
  end

  # Returns provenance for a field with full source metadata for API output.
  #
  # @param field [Symbol, String] The field name
  # @return [Hash, nil] Provenance with source metadata or nil if not tracked
  #
  # @example
  #   airport.provenance_with_source(:timezone)
  #   # => {
  #   #   "source_type" => "OpenStreetMap/TimezoneBoundaryBuilder",
  #   #   "source_id" => nil,
  #   #   "confidence" => 90,
  #   #   "combined_at" => "2024-12-27T15:00:00Z",
  #   #   "source" => {
  #   #     "name" => "Timezone Boundary Builder",
  #   #     "url" => "https://github.com/evansiroky/timezone-boundary-builder",
  #   #     "license" => "ODbL (OpenStreetMap)"
  #   #   }
  #   # }
  def provenance_with_source(field)
    prov = provenance_for(field)
    return nil unless prov

    source_meta = SourceRegistry.for(prov['source_type'])
    return prov unless source_meta

    prov.merge(
      'source' => {
        'name' => source_meta[:name],
        'url' => source_meta[:url],
        'license' => source_meta[:license]
      }.compact
    )
  end

  # Returns all field provenance with source metadata for API output.
  #
  # @return [Hash] All fields with their provenance and source metadata
  def all_provenance_with_sources
    field_provenance.transform_values do |prov|
      source_meta = SourceRegistry.for(prov['source_type'])
      next prov unless source_meta

      prov.merge(
        'source' => {
          'name' => source_meta[:name],
          'url' => source_meta[:url],
          'license' => source_meta[:license]
        }.compact
      )
    end
  end

  # Marks the record as having been combined from sources.
  # Should be called after a combine operation completes.
  def mark_combined!
    update_column(:last_combined_at, Time.current)
  end

  private

  def validate_provenance_columns
    return if self.class.column_names.include?('field_provenance')

    Rails.logger.warn "#{self.class.name} includes HasFieldProvenance but lacks the field_provenance column. " \
                      'Run the add_provenance_to_canonical_tables migration.'
  end
end
