Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.3
  NewCops: pending
  Exclude:
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'lib/tasks/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/ParameterLists:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Layout/LineLength:
  Max: 120
