# frozen_string_literal: true

require 'test_helper'

class EnrichmentAircraftHandlerTest < ActiveSupport::TestCase
  test 'returns found aircraft for a known ICAO' do
    reply = JSON.parse(Enrichment::AircraftHandler.new.call({ icao: aircraft(:one).icao }.to_json))

    assert_equal true, reply['found']
    assert_equal aircraft(:one).icao.downcase, reply['aircraft']['icao']
    assert_not reply.key?('provenance')
  end

  test 'returns found:false for an unknown ICAO' do
    reply = JSON.parse(Enrichment::AircraftHandler.new.call({ icao: 'ZZZZZZ' }.to_json))

    assert_equal({ 'found' => false }, reply)
  end

  test 'includes provenance when requested' do
    record = aircraft(:one)
    record.update_column(:field_provenance, { 'owner' => { 'source_type' => 'AutoGenerated', 'confidence' => 50 } })

    reply = JSON.parse(Enrichment::AircraftHandler.new.call({ icao: record.icao, include: ['provenance'] }.to_json))

    assert reply.key?('provenance')
    assert_equal 50, reply['provenance']['owner']['confidence']
  end

  test 'returns bad_request when ICAO is missing' do
    reply = JSON.parse(Enrichment::AircraftHandler.new.call({}.to_json))

    assert_equal 'bad_request', reply['code']
  end
end
