# frozen_string_literal: true

require 'test_helper'

class EnrichmentProvenanceSerializerTest < ActiveSupport::TestCase
  test 'returns the per-field provenance with source metadata' do
    aircraft = aircraft(:one)
    aircraft.field_provenance = {
      'registration' => {
        'source_type' => 'AutoGenerated',
        'source_id' => nil,
        'confidence' => 50,
        'combined_at' => '2026-01-01T00:00:00Z'
      }
    }

    result = Enrichment::ProvenanceSerializer.call(aircraft)

    assert_equal 50, result['registration']['confidence']
    assert_equal 'AutoGenerated', result['registration']['source_type']
  end

  test 'returns nil for a record that does not track provenance' do
    assert_nil Enrichment::ProvenanceSerializer.call(routes(:aa1))
  end

  test 'returns an empty hash when no fields are tracked' do
    aircraft = aircraft(:one)
    aircraft.field_provenance = {}

    assert_equal({}, Enrichment::ProvenanceSerializer.call(aircraft))
  end
end
